#!/bin/bash
# Auto-deploy, from cron every 2 minutes.
#
# This file is TRACKED. Cron runs the copy in the repo, so a push updates the
# deploy logic itself -- the old version was generated by setup.sh into
# /home/pi/deploy.sh, which made it the one file auto-deploy could never update:
# every change to it needed someone to SSH in and re-run setup.
#
# Everything is inside main() and the last line calls it. That is not style: a
# deploy can replace THIS FILE while it is running, and bash reads a script
# incrementally, so it would resume at a stale byte offset in the new content
# and execute whatever happens to be there. Measured, not theorised -- the
# restart was silently skipped. Wrapping the body in a function forces bash to
# parse to the closing brace before executing anything, and the final line is
# read whole, so the exit is already in hand before main can rewrite the file.
#
# The Pi is a MIRROR of origin/master. It is not a place to edit code.
#
# `git pull` is deliberately NOT used. Pull refuses to overwrite an untracked
# file or a local edit and aborts the whole update, and that refusal caused the
# 2026-09-07 -> 2026-09-12 outage: a commit carried __pycache__/*.pyc, which
# every Pi already has on disk because Python writes it the first time py_new.py
# runs. The pull aborted, HEAD never moved, and the old script restarted the
# service anyway -- every 2 minutes for five days, ~3400 times, no camera firing
# and no error logged anywhere. systemd said active and deploy.log said
# "Deployed <same sha>" at every attempt.
#
# `git fetch` + `git reset --hard` cannot fail that way. Whatever is on the Pi
# is replaced by whatever is on GitHub, untracked collisions included, so no
# future push can wedge a Pi no matter what it contains. Ignored files -- .env,
# new_log.log, last_strong.json -- are never touched.
#
# The trade, on purpose: edits made directly on the Pi are destroyed at the next
# deploy. Change code in git, not on the Pi.

main() {
    # Where this script lives IS the repo, so there is nothing to substitute at
    # install time and the file in git is the file that runs.
    local repo_dir service log before target
    repo_dir="$(cd "$(dirname "$0")" && pwd)"
    service=py_new.service
    log="${DEPLOY_LOG:-/home/pi/deploy.log}"

    cd "$repo_dir" || return 1

    before=$(git rev-parse HEAD)

    if ! git fetch -q origin master 2>/dev/null; then
        echo "$(date): fetch failed - no network? Service left alone." >> "$log"
        return 1
    fi

    target=$(git rev-parse origin/master)
    [ "$before" = "$target" ] && return 0

    if ! git reset -q --hard "$target" 2>> "$log"; then
        echo "$(date): RESET FAILED - still on $(git rev-parse --short HEAD), NOT restarting" >> "$log"
        return 1
    fi

    # Restart only if HEAD actually moved. The old script restarted whenever it
    # thought it was behind, without ever checking that the update had worked.
    [ "$(git rev-parse HEAD)" = "$before" ] && return 0

    sudo systemctl restart "$service"
    echo "$(date): Deployed $(git rev-parse --short HEAD)" >> "$log"
}

main "$@"; exit $?
